baseURL = "https://kkawazoe.github.io/"
languageCode = "jp"
title = "Note To Self ~One Step At A Time~"
theme = "hugo_theme_robust"
enableRobotsTXT = true
googleAnalytics = "UA-46736290-1"

[permalinks]
  post = "/blog/:year/:month/:day/:slug"

[params]
enableHighlight = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
