baseURL = "http://kkawazoe.github.io/"
languageCode = "jp"
title = "My Memorandum For Programming"
theme = "hugo_theme_robust"
enableRobotsTXT = true
googleAnalytics = "UA-46736290-1"
disqusShortname = "http-kkawazoe-github-io"
[permalinks]
  post = "/blog/:year/:month/:day/:slug"
