baseURL = "https://kkawazoe.github.com/"
languageCode = "jp"
title = "Note To Self ~One Step At A Time~"
theme = "hugo_theme_robust"
enableRobotsTXT = true
googleAnalytics = "UA-46736290-1"
[permalinks]
  post = "/blog/:year/:month/:day/:slug"
