name: scheduled_post

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: klakegg/actions-hugo@1.0.0        
    - name: Post build hooks
      run: sh ./.github/scheduled_post.sh
