name: schedulered_post

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Post build hooks
      run: sh ./.github/scheduled_post.sh
